name: CI Pipeline for Tikos Data API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout Repository
      uses: actions/checkout@v3

    - name:  Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name:  Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name:  Test Startup
      run: |
        uvicorn app.main:app --host 127.0.0.1 --port 8000 --lifespan on --reload &
        sleep 5  # Give server time to start
        curl --fail http://127.0.0.1:8000 || exit 1

    - name:  Finished
      run: echo " API started successfully and CI passed!"
